# NumPy 1 – Arrays und Masken

**Szenario:** Die *Kiez Kaffee GmbH* ist eine kleine Berliner Rösterei mit vier Filialen: Kreuzberg, Neukölln, Friedrichshain und Wedding.
Du arbeitest in der Datenanalyse und sollst mit Python die Umsatzdaten auswerten.
In dieser Woche lernst du dafür **NumPy** kennen, das wichtigste Werkzeug für Zahlen in Python.

**Heute:** Was ist NumPy? · Arrays erstellen · Zugriff auf Elemente · Filtern mit Bedingungen (Masken)

# A – Einstieg: Was ist NumPy?

## 1 – NumPy in einem Satz

**NumPy** steht für *Numerical Python*. Es ist eine Bibliothek, mit der man in Python schnell und bequem mit vielen Zahlen auf einmal rechnen kann.

Das Herzstück ist das **Array** (genauer: `ndarray` = *n-dimensionales Array*):
ein Gitter aus Werten, die **alle den gleichen Datentyp** haben, z. B. nur ganze Zahlen oder nur Kommazahlen.

**Warum nicht einfach Python-Listen?**

| | Python-Liste | NumPy-Array |
|---|---|---|
| Geschwindigkeit | langsam bei vielen Zahlen (Python-Schleifen) | sehr schnell (intern in C programmiert) |
| Speicher | jedes Element ist ein eigenes Python-Objekt | Zahlen liegen kompakt hintereinander im Speicher |
| Rechnen | nur mit Schleife | direkt mit dem ganzen Array (**Vektorisierung**) |
| Datentypen | beliebig gemischt | alle Elemente gleicher Typ |

**NumPy ist die Basis für fast alles in der Datenanalyse:** Pandas, Matplotlib, SciPy und scikit-learn bauen alle auf NumPy auf.
Wer NumPy versteht, versteht später auch Pandas viel leichter.

## 2 – Installation und erster Test

NumPy gehört **nicht** zum Standard-Python, du musst es einmal installieren.

**Schritt 1:** Terminal in VS Code öffnen und prüfen, dass deine virtuelle Umgebung aktiv ist.
Vor der Eingabezeile steht dann `(.venv)`. Falls nicht:

```
.venv\Scripts\activate
```

**Schritt 2:** NumPy installieren:

```
pip install numpy
```

**Schritt 3:** Oben rechts im Notebook den **Kernel** prüfen. Dort muss die Python-Version aus deinem `.venv` ausgewählt sein.

**Schritt 4:** Die folgende Zelle ausführen. Wenn eine Versionsnummer erscheint, hat alles geklappt.

> 💡 **Kurz erwähnt – `ModuleNotFoundError: No module named 'numpy'`**
> Das heißt fast immer: NumPy wurde in einer *anderen* Umgebung installiert als der, die das Notebook gerade benutzt.
> Lösung: Kernel oben rechts auf das `.venv` umstellen, oder im Notebook einmal `%pip install numpy` ausführen.

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np   # "np" ist die übliche Abkürzung – so schreibt es die ganze Welt

print("NumPy-Version:", np.__version__)

NumPy-Version: 2.5.3


## 3 – Liste gegen Array: der Unterschied auf einen Blick

Kiez Kaffee hat drei Preise für Kaffeesorten (in €). Was passiert, wenn wir sie mit 2 multiplizieren?

In [4]:
preise_liste = [4.50, 3.20, 5.80]
preise_array = np.array([4.50, 3.20, 5.80])

print("Liste * 2:", preise_liste * 2)   # Liste wird VERDOPPELT (aneinandergehängt)
print("Array * 2:", preise_array * 2)   # jede Zahl wird mit 2 multipliziert

Liste * 2: [4.5, 3.2, 5.8, 4.5, 3.2, 5.8]
Array * 2: [ 9.   6.4 11.6]


Bei der Liste bräuchte man für „jeden Preis verdoppeln" eine Schleife:

In [5]:
# Liste: Schleife nötig
doppelt = [p * 2 for p in preise_liste]
print(doppelt)

# Array: eine Zeile, keine Schleife
print(preise_array * 2)

[9.0, 6.4, 11.6]
[ 9.   6.4 11.6]


Genau das ist die **Vektorisierung**: Eine Rechenoperation wird automatisch auf **jedes Element** angewendet.
Das ist kürzer, besser lesbar und bei großen Datenmengen viel schneller.

### Übung 1 – Preiserhöhung

👥 **Gemeinsame Übung**

Kiez Kaffee erhöht alle Preise um 10 %.

1. Berechne die neuen Preise mit der **Liste** `preise_liste` (Tipp: List Comprehension).
2. Berechne die neuen Preise mit dem **Array** `preise_array`.
3. Welche Variante ist kürzer?

In [6]:
# Dein Code hier
preise_liste = [4.50, 3.20, 5.80]
preise_array = np.array([4.50, 3.20, 5.80])

# 1
neu_liste = [e * 1.1 for e in preise_liste]
print(neu_liste)
print()

# 2
neu_array = preise_array * 1.1
print(neu_array)
print()

[4.95, 3.5200000000000005, 6.38]

[4.95 3.52 6.38]



# B – Brücke zur Mathe: Boolesche Algebra

## 4 – Von der Wahrheitstabelle zum Bool-Array

Heute Vormittag hast du die Verknüpfungen **UND**, **ODER** und **NICHT** kennengelernt.
In NumPy gibt es dafür eigene Zeichen, die **elementweise** auf ganze Arrays wirken:

| Mathe | Python (einzelne Werte) | NumPy (Arrays) |
|---|---|---|
| A ∧ B (UND) | `a and b` | `a & b` |
| A ∨ B (ODER) | `a or b` | `a \| b` |
| ¬A (NICHT) | `not a` | `~a` |

Damit können wir die komplette Wahrheitstabelle in einem Schritt berechnen:

In [7]:
A = np.array([True, True, False, False])
B = np.array([True, False, True, False])

print("A      :", A)
print("B      :", B)
print("A UND B:", A & B)    # T F F F
print("A ODER B:", A | B)   # T T T F
print("NICHT A:", ~A)       # F F T T

A      : [ True  True False False]
B      : [ True False  True False]
A UND B: [ True False False False]
A ODER B: [ True  True  True False]
NICHT A: [False False  True  True]


Jede Spalte der Wahrheitstabelle ist jetzt ein Array. NumPy rechnet alle vier Zeilen gleichzeitig aus.

Später benutzen wir genau diese Bool-Arrays, um Daten zu **filtern**, zum Beispiel „alle Tage mit Umsatz über 1000 € **UND** am Wochenende".

### Übung 2 – XOR-Tabelle

👥 **Gemeinsame Übung**

Das **exklusive ODER** (XOR) ist wahr, wenn **genau einer** der beiden Werte wahr ist.

1. Berechne XOR für `A` und `B` mit `&`, `|` und `~` (Tipp: *A ODER B, aber NICHT A UND B*).
2. NumPy kennt dafür auch ein eigenes Zeichen: `^`. Prüfe, ob du das gleiche Ergebnis bekommst.

In [8]:
# Dein Code hier
# 1 selbst gebaut
xor = (A | B) & ~(A & B)
print(xor)
print()

# 2 XOR-Operator
print(A ^ B)

[False  True  True False]

[False  True  True False]


# C – Arrays erstellen

## 5 – Aus Listen: `np.array()`

Der einfachste Weg: Eine Python-Liste wird in ein Array umgewandelt.
Eine **verschachtelte Liste** (Liste von Listen) ergibt ein **2D-Array**, also eine Tabelle mit Zeilen und Spalten.

In [9]:
# 1D: Tagesumsätze einer Filiale (Mo–Fr)
umsatz_woche = np.array([820, 950, 780, 1100, 1340])
print(umsatz_woche)
print()

# 2D: Umsätze von 2 Filialen (Zeilen) an 3 Tagen (Spalten)
umsatz_tabelle = np.array([
    [820, 950, 780],     # Kreuzberg
    [610, 700, 690],     # Neukölln
])
print(umsatz_tabelle)

[ 820  950  780 1100 1340]

[[820 950 780]
 [610 700 690]]


## 6 – Platzhalter: `np.zeros`, `np.ones`, `np.full`

Oft braucht man ein Array einer bestimmten Größe, das man später befüllt.
Die Größe gibt man als **Tupel** an: `(Zeilen, Spalten)`.

| Funktion | Ergebnis |
|---|---|
| `np.zeros((2, 3))` | 2×3-Array voller Nullen |
| `np.ones((2, 3))` | 2×3-Array voller Einsen |
| `np.full((2, 3), 7)` | 2×3-Array, überall der Wert 7 |

In [10]:
print(np.zeros((2, 3)))
print()
print(np.ones((2, 3)))
print()
print(np.full((2, 3), 7))

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[7 7 7]
 [7 7 7]]


> 💡 **Kurz erwähnt – `np.empty`**
> `np.empty((2, 3))` erstellt ein Array, ohne die Werte vorher zu setzen. Darin steht dann zufälliger „Müll" aus dem Speicher.
> Das ist minimal schneller, aber für uns nicht wichtig. Nimm lieber `zeros` oder `full`.

## 7 – Zahlenfolgen: `np.arange` und `np.linspace`

| Funktion | Bedeutung | Ende enthalten? |
|---|---|---|
| `np.arange(start, stop, schritt)` | wie Pythons `range()`, aber als Array | **nein** |
| `np.linspace(start, stop, anzahl)` | *anzahl* gleichmäßig verteilte Werte | **ja** |

Merkhilfe: Bei `arange` gibst du den **Abstand** vor, bei `linspace` die **Anzahl**.

In [11]:
print(np.arange(0, 10, 2))       # 0, 2, 4, 6, 8   (10 ist NICHT dabei)
print(np.linspace(0, 10, 5))     # 5 Werte von 0 bis 10, beide Enden dabei

[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


## 8 – Zufallszahlen

Zum Üben brauchen wir oft Beispieldaten. Die moderne Art in NumPy ist ein **Zufallsgenerator**:

```python
rng = np.random.default_rng(42)   # 42 = "Seed": gleiche Zahl -> gleiche Zufallszahlen
```

| Methode | Ergebnis |
|---|---|
| `rng.integers(low, high, size)` | ganze Zahlen von `low` bis **unter** `high` |
| `rng.random(size)` | Kommazahlen zwischen 0 und 1 |

Der **Seed** sorgt dafür, dass alle in der Klasse die gleichen „Zufalls"-Zahlen bekommen. So kann man Ergebnisse vergleichen.

In [12]:
rng = np.random.default_rng(42)

print(rng.integers(1, 7, size=10))        # 10 Würfelwürfe
print()
print(rng.integers(0, 100, size=(2, 4)))  # 2x4-Array mit Zahlen von 0 bis 99

[1 5 4 3 3 6 1 5 2 1]

[[52 97 73 76]
 [71 78 51 12]]


> 💡 **Kurz erwähnt:** In älteren Tutorials findest du oft `np.random.randint(...)` oder `np.random.rand(...)`.
> Das funktioniert noch, gilt aber als veraltet. Wir benutzen `default_rng`.

### Übung 3 – Arrays erstellen

👥 **Gemeinsame Übung**

1. Erstelle ein 1D-Array mit den Zahlen von **5 bis 15** (15 soll dabei sein).
2. Erstelle ein **3×4-Array**, das überall den Wert **7.5** enthält.
3. Erstelle ein Array mit **10 Werten**, die gleichmäßig zwischen **0 und 100** verteilt sind.
4. Erstelle mit `rng` ein **5×5-Array** mit zufälligen ganzen Zahlen von **0 bis 9**.

In [38]:
# Dein Code hier
# 1
a1 = np.arange(5, 16)
print(a1)
print()

# 2
a2 = np.full((3, 4), 7.5)
print(a2)
print()

# 3
a3 = np.linspace(0, 100, 10)
print(a3)
print()

# 4
a4 = rng.integers(0, 10, size=(5, 5))
print(a4)


[ 5  6  7  8  9 10 11 12 13 14 15]

[[7.5 7.5 7.5 7.5]
 [7.5 7.5 7.5 7.5]
 [7.5 7.5 7.5 7.5]]

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]

[[1 5 6 8 6]
 [4 4 3 1 2]
 [1 2 8 5 0]
 [4 2 6 8 0]
 [4 4 9 3 1]]


# D – Eigenschaften, Indexing und Slicing

## 9 – Wichtige Eigenschaften eines Arrays

Jedes Array „weiß" etwas über sich selbst:

| Attribut | Bedeutung | Beispiel für eine 2×3-Tabelle |
|---|---|---|
| `.ndim` | Anzahl der Dimensionen (Achsen) | `2` |
| `.shape` | Größe pro Dimension als Tupel `(Zeilen, Spalten)` | `(2, 3)` |
| `.size` | Gesamtzahl der Elemente | `6` |
| `.dtype` | Datentyp der Elemente | `int64` |

In [14]:
# 2D: Umsätze von 2 Filialen (Zeilen) an 3 Tagen (Spalten)
umsatz_tabelle = np.array([
    [820, 950, 780],     # Kreuzberg
    [610, 700, 690],     # Neukölln
])

print("ndim :", umsatz_tabelle.ndim)
print("shape:", umsatz_tabelle.shape)
print("size :", umsatz_tabelle.size)
print("dtype:", umsatz_tabelle.dtype)

ndim : 2
shape: (2, 3)
size : 6
dtype: int64


**Achtung bei der Shape:** Diese drei sehen ähnlich aus, sind aber verschieden:

| Shape | Bedeutung |
|---|---|
| `(3,)` | 1D-Array mit 3 Elementen (eine einfache Reihe) |
| `(1, 3)` | 2D-Array: **1 Zeile**, 3 Spalten |
| `(3, 1)` | 2D-Array: 3 Zeilen, **1 Spalte** |

In [15]:
print(np.array([1, 2, 3]).shape)          # (3,)
print(np.array([[1, 2, 3]]).shape)        # (1, 3)
print(np.array([[1], [2], [3]]).shape)    # (3, 1)

(3,)
(1, 3)
(3, 1)


## 10 – Indexing: einzelne Elemente

Wie bei Listen beginnt die Zählung bei **0**. Negative Indizes zählen von hinten.

Bei 2D-Arrays gibt man **Zeile, Spalte** an:

- `arr[0, 2]` → Zeile 0, Spalte 2 (empfohlene Schreibweise)
- `arr[0][2]` → funktioniert auch: erst Zeile 0 holen, dann daraus Element 2

In [16]:
umsatz_woche = np.array([820, 950, 780, 1100, 1340])
print(umsatz_woche[0])     # erster Tag - 820
print(umsatz_woche[-1])    # letzter Tag - 1340

# 2D: Umsätze von 2 Filialen (Zeilen) an 3 Tagen (Spalten)
umsatz_tabelle = np.array([
    [820, 950, 780],     # Kreuzberg
    [610, 700, 690],     # Neukölln
])

print(umsatz_tabelle[1, 2])   # Neukölln, Tag 3 - 690
print(umsatz_tabelle[1][2])   # gleiches Ergebnis - 690

820
1340
690
690


## 11 – Slicing: Teilbereiche ausschneiden

Schreibweise: `[start:stop:schritt]`, **stop ist nicht enthalten**.

Bei 2D-Arrays gibt es einen Slice für **jede Dimension**, getrennt durch ein Komma: `arr[zeilen, spalten]`.
Ein einzelner Doppelpunkt `:` bedeutet „alles".

| Ausdruck | Ergebnis |
|---|---|
| `arr[1:4]` | Elemente 1, 2, 3 |
| `arr[::2]` | jedes zweite Element |
| `arr2d[0, :]` | ganze Zeile 0 |
| `arr2d[:, 1]` | ganze Spalte 1 |
| `arr2d[:2, 1:]` | Zeilen 0–1, ab Spalte 1 |

In [17]:
umsatz_woche = np.array([820, 950, 780, 1100, 1340])
print(umsatz_woche[1:4])      # Di bis Do - 950 780 1100
print(umsatz_woche[::2])      # Mo, Mi, Fr

# 2D: Umsätze von 2 Filialen (Zeilen) an 3 Tagen (Spalten)
umsatz_tabelle = np.array([
    [820, 950, 780],     # Kreuzberg
    [610, 700, 690],     # Neukölln
])
print(umsatz_tabelle[0, :])   # alle Tage von Kreuzberg
print(umsatz_tabelle[:, 1])   # Tag 2 von allen Filialen

[ 950  780 1100]
[ 820  780 1340]
[820 950 780]
[950 700]


> 💡 **Kurz erwähnt – Slices sind „Fenster", keine Kopien**
> Ein Slice zeigt auf **dieselben Daten** wie das Original (man nennt das eine *View*).
> Änderst du den Slice, änderst du auch das Original!
> Wenn du wirklich eine unabhängige Kopie brauchst: `.copy()` anhängen.

In [40]:
original = np.array([10, 20, 30, 40])

fenster = original[0:2]       # View: 10 20
fenster[0] = 999              # 999 20  
print("Original nach Änderung am Slice:", original)   # 999 steht jetzt auch im Original!

original = np.array([10, 20, 30, 40])

kopie = original[0:2].copy()  # echte Kopie
print("Original nach Änderung an Kopie:", original)   # unverändert

Original nach Änderung am Slice: [999  20  30  40]
Original nach Änderung an Kopie: [10 20 30 40]


Für die nächste Übung erzeugen wir eine 5×5-Matrix mit den Zahlen 1 bis 25:

In [19]:
matrix = np.arange(1, 26).reshape(5, 5)   # reshape lernst du in Notebook 5 genauer kennen
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### Übung 4 – Indexing und Slicing

👥 **Gemeinsame Übung**

Arbeite mit `matrix`:

1. Wähle die Zahl **13** aus.
2. Wähle die **zweite Zeile** aus (Ergebnis: `[ 6  7  8  9 10]`).
3. Wähle die **letzten beiden Spalten** aus.
4. Schneide ein Teil-Array aus, das die Zahlen **12, 13, 17, 18** enthält.

In [46]:
# Dein Code hier
# 1
print(matrix[2, 2])
print()
# 2
print(matrix[1, :])
print()
# 3
print(matrix[:, -2:])
print()
# 4
print(matrix[2:4, 1:3])
print()

13

[ 6  7  8  9 10]

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]

[[12 13]
 [17 18]]



# E – Vergleiche und Boolean Indexing (Masken)

## 12 – Vergleiche liefern Bool-Arrays

Vergleichsoperatoren (`>`, `<`, `>=`, `<=`, `==`, `!=`) wirken ebenfalls **elementweise**.
Das Ergebnis ist ein Array aus `True` und `False`, genau wie die Wahrheitswerte aus Block B.

In [21]:
umsatz_woche = np.array([820, 950, 780, 1100, 1340])
print(umsatz_woche)
print(umsatz_woche > 900)

[ 820  950  780 1100 1340]
[False  True False  True  True]


## 13 – Boolean Indexing: mit einer Maske filtern

Ein Bool-Array nennt man in diesem Zusammenhang **Maske**. Setzt man die Maske in eckige Klammern,
bekommt man **nur die Elemente, bei denen `True` steht**:

```python
arr[maske]
```

In [22]:
umsatz_woche = np.array([820, 950, 780, 1100, 1340])
maske = umsatz_woche > 900
print("Maske      :", maske)
print("Gefiltert  :", umsatz_woche[maske])

# Meist schreibt man es direkt in einer Zeile:
print("Kurzform   :", umsatz_woche[umsatz_woche > 900])

Maske      : [False  True False  True  True]
Gefiltert  : [ 950 1100 1340]
Kurzform   : [ 950 1100 1340]


Bei 2D-Arrays funktioniert das genauso. Das Ergebnis ist dann immer ein **1D-Array** mit allen Treffern:

In [47]:
# 2D: Umsätze von 2 Filialen (Zeilen) an 3 Tagen (Spalten)
umsatz_tabelle = np.array([
    [820, 950, 780],     # Kreuzberg
    [610, 700, 690],     # Neukölln
])
print(umsatz_tabelle[umsatz_tabelle < 800])

[780 610 700 690]


## 14 – Bedingungen kombinieren: `&`, `|`, `~`

Hier kommt die Boolesche Algebra zurück. Zwei Regeln sind wichtig:

1. Für Arrays **immer** `&`, `|`, `~` benutzen, **nicht** `and`, `or`, `not`.
2. Jede Einzelbedingung **in Klammern** setzen!

In [24]:
umsatz_woche = np.array([820, 950, 780, 1100, 1340])

# Richtig: Klammern um jede Bedingung
print(umsatz_woche[(umsatz_woche > 800) & (umsatz_woche < 1200)])

# ODER: sehr niedrige oder sehr hohe Umsätze
print(umsatz_woche[(umsatz_woche < 800) | (umsatz_woche > 1200)])

# NICHT: alles außer über 1000
print(umsatz_woche[~(umsatz_woche > 1000)])

[ 820  950 1100]
[ 780 1340]
[820 950 780]


**Die typischen Fehler**, damit du die Meldung erkennst, wenn sie bei dir auftaucht:

In [25]:
# Fehler 1: "and" statt "&"
try:
    umsatz_woche[(umsatz_woche > 800) and (umsatz_woche < 1200)]
except ValueError as e:
    print("Fehler 1:", e)

# Fehler 2: Klammern vergessen
try:
    umsatz_woche[umsatz_woche > 800 & umsatz_woche < 1200]
except ValueError as e:
    print("Fehler 2:", e)

Fehler 1: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Fehler 2: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


Die Meldung *„The truth value of an array ... is ambiguous"* bedeutet fast immer: `and`/`or` benutzt oder Klammern vergessen.

## 15 – Werte per Maske ersetzen

Eine Maske kann auch links vom `=` stehen. Dann werden **nur die markierten Elemente** überschrieben:

In [26]:
messwerte = np.array([12, -3, 8, -1, 15])
messwerte[messwerte < 0] = 0      # alle negativen Werte auf 0 setzen
print(messwerte)

[12  0  8  0 15]


### Übung 5 – Filtern in der Matrix

👥 **Gemeinsame Übung**

Arbeite wieder mit `matrix` (Zahlen 1–25).

1. Wähle alle Elemente aus, die **größer als 15** sind.
2. Wähle alle **geraden** Zahlen aus (Tipp: `% 2 == 0`).
3. Wähle alle Zahlen aus, die **zwischen 5 und 10** liegen (beide eingeschlossen).
4. Wähle alle Zahlen aus, die **kleiner als 4 oder größer als 22** sind.

In [49]:
# Dein Code hier
matrix = np.arange(1, 26).reshape(5, 5)   # reshape lernst du in Notebook 5 genauer kennen
print(matrix)
# 1
print(matrix[matrix > 15])
# 2
print(matrix[matrix % 2 == 0])
# 3
print(matrix[(matrix >= 5) & (matrix <= 10)])
# 4
print(matrix[(matrix < 4) | (matrix > 22)])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[16 17 18 19 20 21 22 23 24 25]
[ 2  4  6  8 10 12 14 16 18 20 22 24]
[ 5  6  7  8  9 10]
[ 1  2  3 23 24 25]


# F – Übungen zum selbstständigen Arbeiten

Hier übst du allein oder zu zweit. Die Übungen sind nach **Themen** sortiert.
Bei jeder Übung steht, zu welchem Block sie gehört. Wenn du bei einer Aufgabe hängst, schau im passenden Block nach.

## 16 – Daten für die Übungen

Führe diese Zelle zuerst aus. Sie erzeugt alle Daten, die du in diesem Block brauchst:

- `umsatz`: Umsätze (in €) der **4 Filialen** (Zeilen) an **7 Tagen** Mo–So (Spalten)
- `kb_umsatz`: Tagesumsätze der Filiale Kreuzberg über **4 Wochen (28 Tage)**. An zwei Tagen gab es einen **Buchungsfehler** (negativer Wert).
- `wochenende`: Maske, die für jeden der 28 Tage angibt, ob Sa oder So ist

In [28]:
filialen = np.array(["Kreuzberg", "Neukölln", "Friedrichshain", "Wedding"])
tage = np.array(["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"])

rng = np.random.default_rng(7)
umsatz = rng.integers(500, 1500, size=(4, 7))

rng = np.random.default_rng(2026)
kb_umsatz = rng.integers(600, 1600, size=28)
kb_umsatz[3] = -120     # Buchungsfehler
kb_umsatz[17] = -45     # Buchungsfehler

wochenende = np.array([False, False, False, False, False, True, True] * 4)

print(umsatz)
print(kb_umsatz)

[[1444 1125 1184 1397 1078 1275 1333]
 [ 725  555  800  785 1373 1412  505]
 [ 999 1321  631 1297  619  967 1316]
 [ 803  841  778 1219  754 1490  945]]
[1451  778  626 -120  965 1067  679  970 1243  954 1431 1390 1304 1505
 1321  777 1458  -45  698  898  765 1566 1327 1519  882 1235 1204 1352]


## 17 – Thema: Liste vs. Array

### Übung 6 – Röstmengen umrechnen

📌 **Thema:** Liste vs. Array (Block A)

Die Rösterei notiert ihre Röstmengen in **Gramm**: `[2500, 1800, 3200, 950]`.

1. Rechne die Mengen mit einer **Liste** in **Kilogramm** um.
2. Rechne sie mit einem **Array** in Kilogramm um.
3. Was passiert, wenn du die Liste mit `+ 100` erhöhen willst? Und beim Array? (Ausprobieren und Fehlermeldung lesen!)

In [29]:
# Dein Code hier

## 18 – Thema: Boolesche Algebra

### Übung 7 – Rabattregel

📌 **Thema:** Boolesche Algebra (Block B)

Kiez Kaffee gibt Rabatt nach folgender Regel:

> Rabatt gibt es, wenn jemand **Stammkunde** ist **UND** (am **Wochenende** bestellt **ODER** eine **Großbestellung** aufgibt).

Für sechs Bestellungen gilt:
```python
stammkunde     = np.array([True,  True,  False, True,  False, True ])
am_wochenende  = np.array([False, True,  True,  False, False, False])
grossbestellung = np.array([True,  False, True,  False, True,  False])
```

1. Berechne ein Bool-Array `rabatt` nach der Regel.
2. Berechne, welche Bestellungen **keinen** Rabatt bekommen.
3. Was ändert sich, wenn du die Klammern weglässt: `stammkunde & am_wochenende | grossbestellung`? Warum?

In [30]:
# Dein Code hier

## 19 – Thema: Arrays erstellen

### Übung 8 – Kassenbuch vorbereiten

📌 **Thema:** Arrays erstellen (Block C)

1. Erstelle ein leeres Kassenbuch für **4 Filialen × 7 Tage**, gefüllt mit Nullen.
2. Erstelle ein Array mit den **Bestellnummern 1001 bis 1020**.
3. Der Röstofen soll in **6 gleichmäßigen Stufen** von **180 °C bis 230 °C** hochheizen. Erstelle die Temperaturstufen.
4. Erstelle ein Array mit **28 Einträgen**, die alle den Standardpreis **4.50** haben.

In [31]:
# Dein Code hier

### Übung 9 – Testdaten mit Seed

📌 **Thema:** Arrays erstellen (Block C)

1. Erzeuge mit `np.random.default_rng(1)` die Bestellmengen von **10 Bestellungen** (jeweils **1 bis 5** Packungen).
2. Führe die Zelle mehrmals aus. Ändern sich die Zahlen?
3. Erzeuge einen **neuen** Generator mit Seed `1` und ziehe noch einmal 10 Mengen. Vergleiche mit Aufgabe 1.

In [32]:
# Dein Code hier

## 20 – Thema: Eigenschaften, Indexing und Slicing

### Übung 10 – Filialdaten auslesen

📌 **Thema:** Eigenschaften, Indexing und Slicing (Block D)

Arbeite mit `umsatz` (Zeilen = Filialen, Spalten = Tage).

1. Gib `shape` und `size` aus. Was bedeuten die Zahlen hier?
2. Wie viel Umsatz machte **Friedrichshain am Freitag**?
3. Gib alle Umsätze von **Wedding** aus.
4. Gib die **Wochenend-Umsätze (Sa, So)** aller Filialen aus.

In [33]:
# Dein Code hier

### Übung 11 – Vier Wochen Kreuzberg: Zeiträume

📌 **Thema:** Eigenschaften, Indexing und Slicing (Block D)

Arbeite mit `kb_umsatz` (28 Tage, jeweils Mo–So).

1. Gib `shape` und `dtype` aus.
2. Gib die Umsätze der **ersten Woche** aus.
3. Gib die Umsätze der **letzten Woche** aus (Tipp: negativer Index).
4. Gib nur die Umsätze **jedes Montags** aus (Tipp: Schrittweite).

In [34]:
# Dein Code hier

## 21 – Thema: Vergleiche und Masken

### Übung 12 – Filialen filtern

📌 **Thema:** Vergleiche und Masken (Block E)

Arbeite mit `umsatz` (4 Filialen × 7 Tage).

1. Gib alle Tagesumsätze aus, die **über 1200 €** liegen.
2. Gib alle Tagesumsätze von **Neukölln** aus, die **unter 900 €** liegen.
3. Gib die **Namen der Filialen** aus, die am **Samstag über 1000 €** Umsatz hatten.
   (Tipp: Maske aus der Samstag-Spalte bauen und damit `filialen` filtern.)

In [35]:
# Dein Code hier

### Übung 13 – Vier Wochen Kreuzberg: Auswertung

📌 **Thema:** Vergleiche und Masken (Block E)

Arbeite mit `kb_umsatz` und der Maske `wochenende`.

1. Setze alle **negativen Werte auf 0**.
2. Gib alle Umsätze aus, die **über 1200 €** liegen **und** an einem **Wochenende** waren.
3. Gib alle Umsätze an **Werktagen** (also **nicht** Wochenende) aus, die **unter 800 €** liegen.
4. **Bonus:** An wie vielen Tagen lag der Umsatz über 1200 €? (Tipp: `len()` auf das gefilterte Ergebnis)

In [36]:
# Dein Code hier

---
**Morgen:** Mengenlehre trifft NumPy: Kunden-IDs vergleichen, Duplikate finden und mit `np.where` Werte bedingt ersetzen.